import ReactMarkdown from "react-markdown";
import { Loader2, MessageSquare, NotebookPen, Target, Trash2 } from "lucide-react";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { StudyGuide } from "./useStudyGuides";

interface Props {
  guide: StudyGuide | null;
  generating: boolean;
  onClose: () => void;
  onDrill: (guide: StudyGuide) => void;
  onAskAtlas: (guide: StudyGuide) => void;
  onDelete: (guide: StudyGuide) => void;
}

/** Journey step 2: the generated guide, with the drill hand-off. */
const StudyGuideSheet = ({ guide, generating, onClose, onDrill, onAskAtlas, onDelete }: Props) => (
  <Sheet open={!!guide || generating} onOpenChange={(o) => !o && onClose()}>
    <SheetContent side="right" className="w-full sm:max-w-2xl overflow-y-auto">
      {generating && !guide ? (
        <div className="h-full flex flex-col items-center justify-center text-center gap-3">
          <Loader2 className="h-6 w-6 animate-spin text-primary" />
          <p className="font-medium">ATLAS is writing your study guide</p>
          <p className="text-sm text-muted-foreground max-w-xs">
            High-yield essentials, mechanisms, exam traps and a 30-minute block.
          </p>
        </div>
      ) : guide ? (
        <>
          <SheetHeader>
            <SheetTitle className="flex items-start gap-2">
              <NotebookPen className="h-4 w-4 text-primary mt-1 flex-shrink-0" />
              <span>{guide.title}</span>
            </SheetTitle>
            <SheetDescription>
              {guide.subject ? `${guide.subject} · ` : ""}Generated by ATLAS · saved to your guides
            </SheetDescription>
          </SheetHeader>

          {guide.focus_areas?.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mt-4">
              {guide.focus_areas.map((f) => <Badge key={f} variant="secondary">{f}</Badge>)}
            </div>
          )}

          <div className="flex flex-wrap gap-2 mt-4">
            <Button size="sm" className="rounded-full" onClick={() => onDrill(guide)}>
              <Target className="h-3.5 w-3.5 mr-1.5" /> Do questions
            </Button>
            <Button size="sm" variant="outline" className="rounded-full" onClick={() => onAskAtlas(guide)}>
              <MessageSquare className="h-3.5 w-3.5 mr-1.5" /> Ask ATLAS
            </Button>
            <Button
              size="sm"
              variant="ghost"
              className="rounded-full text-muted-foreground"
              onClick={() => { onDelete(guide); onClose(); }}
            >
              <Trash2 className="h-3.5 w-3.5 mr-1.5" /> Delete
            </Button>
          </div>

          <article className="prose prose-sm max-w-none mt-5 pb-10">
            <ReactMarkdown>{guide.content}</ReactMarkdown>
          </article>
        </>
      ) : null}
    </SheetContent>
  </Sheet>
);

export default StudyGuideSheet;
