// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-qbank-questions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { z } from "npm:zod@^3.25.76";
function admin(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) return "Not authenticated";
  const sb2 = admin(ctx);
  const { data, error } = await sb2.rpc("has_role", { _user_id: ctx.getUserId(), _role: "platform_admin" });
  if (error) return error.message;
  if (!data) return "Platform admin role required to review content.";
  return null;
}
var list_qbank_questions_default = defineTool({
  name: "list_qbank_questions",
  title: "List QBank questions",
  description: "List QBank vignettes for review. Filter by specialty, subject, system, difficulty. Returns id, question_id, subject, system, difficulty, stem preview.",
  inputSchema: {
    subject: z.string().optional().describe("Filter by subject (e.g. 'Cardiology')."),
    system: z.string().optional().describe("Filter by organ system."),
    difficulty: z.enum(["easy", "medium", "hard"]).optional(),
    limit: z.number().int().min(1).max(100).default(25),
    offset: z.number().int().min(0).default(0)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    let q = admin(ctx).from("qbank_questions").select("id, question_id, subject, system, difficulty, stem, first_aid_reference, is_active").eq("is_active", true).order("question_id").range(input.offset, input.offset + input.limit - 1);
    if (input.subject) q = q.eq("subject", input.subject);
    if (input.system) q = q.eq("system", input.system);
    if (input.difficulty) q = q.eq("difficulty", input.difficulty);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({ ...r, stem_preview: r.stem.slice(0, 200) }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: rows.length, questions: rows.map(({ stem, ...rest }) => rest) }, null, 2) }],
      structuredContent: { questions: rows }
    };
  }
});

// src/lib/mcp/tools/get-qbank-question.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_qbank_question_default = defineTool2({
  name: "get_qbank_question",
  title: "Get QBank question",
  description: "Fetch a full QBank vignette including stem, options, correct answer, explanation, First Aid reference. Use to review clinical accuracy against gold-standard sources.",
  inputSchema: {
    question_id: z2.string().describe("The public question_id (e.g. 'QB-0042') or UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ question_id }, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    const sb2 = admin(ctx);
    const isUuid = /^[0-9a-f-]{36}$/i.test(question_id);
    const { data, error } = await sb2.from("qbank_questions").select("*").eq(isUuid ? "id" : "question_id", question_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Question not found" }], isError: true };
    const opts = data.options ?? [];
    const pretty = [
      `# ${data.question_id} \u2014 ${data.subject} / ${data.system} (${data.difficulty})`,
      "",
      "## Stem",
      data.stem,
      "",
      "## Options",
      ...opts.map((o, i) => `${String.fromCharCode(65 + i)}. ${o}${i === data.correct_answer_index ? "  \u2190 CORRECT" : ""}`),
      "",
      "## Explanation",
      data.explanation,
      "",
      data.first_aid_reference ? `**First Aid ref:** ${data.first_aid_reference}` : ""
    ].filter(Boolean).join("\n");
    return {
      content: [{ type: "text", text: pretty }],
      structuredContent: { question: data }
    };
  }
});

// src/lib/mcp/tools/search-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var search_content_default = defineTool3({
  name: "search_content",
  title: "Search QBank content",
  description: "Full-text search QBank stems, explanations, and topics. Use to find items by concept, drug name, disease, or guideline.",
  inputSchema: {
    query: z3.string().min(2).describe("Search phrase."),
    limit: z3.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    const like = `%${query.replace(/[%_]/g, "\\$&")}%`;
    const { data, error } = await admin(ctx).from("qbank_questions").select("id, question_id, subject, system, difficulty, stem, first_aid_reference").eq("is_active", true).or(`stem.ilike.${like},explanation.ilike.${like},topic.ilike.${like}`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({ ...r, stem_preview: r.stem.slice(0, 180) }));
    return {
      content: [{ type: "text", text: JSON.stringify({ count: rows.length, matches: rows.map(({ stem, ...rest }) => rest) }, null, 2) }],
      structuredContent: { matches: rows }
    };
  }
});

// src/lib/mcp/tools/get-atlas-conversation.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_atlas_conversation_default = defineTool4({
  name: "get_atlas_conversation",
  title: "Get ATLAS conversation",
  description: "Fetch a full ATLAS AI tutor conversation (Socratic dialogue) for review of pedagogy and clinical accuracy.",
  inputSchema: {
    conversation_id: z4.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ conversation_id }, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    const sb2 = admin(ctx);
    const { data: convo, error: cErr } = await sb2.from("eli_conversations").select("*").eq("id", conversation_id).maybeSingle();
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    if (!convo) return { content: [{ type: "text", text: "Conversation not found" }], isError: true };
    const { data: msgs, error: mErr } = await sb2.from("eli_messages").select("role, content, created_at").eq("conversation_id", conversation_id).order("created_at");
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    const transcript = (msgs ?? []).map((m) => `**${m.role.toUpperCase()}:**
${m.content}`).join("\n\n---\n\n");
    return {
      content: [{ type: "text", text: `# Conversation ${conversation_id}

${transcript}` }],
      structuredContent: { conversation: convo, messages: msgs }
    };
  }
});

// src/lib/mcp/tools/list-atlas-conversations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_atlas_conversations_default = defineTool5({
  name: "list_atlas_conversations",
  title: "List recent ATLAS conversations",
  description: "List recent ATLAS AI tutor conversations for sampling review.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    const { data, error } = await admin(ctx).from("eli_conversations").select("id, title, user_id, created_at, updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, conversations: data }, null, 2) }],
      structuredContent: { conversations: data }
    };
  }
});

// src/lib/mcp/tools/get-course-quiz.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z6 } from "npm:zod@^3.25.76";
var get_course_quiz_default = defineTool6({
  name: "get_course_quiz",
  title: "Get course quiz",
  description: "Fetch a course quiz (assessment) with all its questions for accuracy review.",
  inputSchema: {
    quiz_id: z6.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ quiz_id }, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    const { data, error } = await admin(ctx).from("course_quizzes").select("*").eq("id", quiz_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Quiz not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { quiz: data }
    };
  }
});

// src/lib/mcp/tools/flag-content.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z7 } from "npm:zod@^3.25.76";
var flag_content_default = defineTool7({
  name: "flag_content_for_review",
  title: "Flag content for review",
  description: "Log a review verdict on a QBank question, assessment item, ATLAS conversation, or course quiz. Records reviewer, verdict, severity, sources cross-checked, and notes to the content_reviews audit trail.",
  inputSchema: {
    content_type: z7.enum(["qbank_question", "assessment_item", "atlas_conversation", "course_quiz"]),
    content_id: z7.string().describe("question_id, UUID, or conversation_id."),
    verdict: z7.enum(["approved", "needs_revision", "rejected", "flagged"]),
    severity: z7.enum(["low", "medium", "high", "critical"]).default("medium"),
    reason: z7.string().optional().describe("Short category, e.g. 'incorrect answer', 'outdated guideline', 'weak distractors'."),
    sources_checked: z7.array(z7.string()).default([]).describe("Sources cross-referenced, e.g. ['First Aid 2024 p.312', 'UpToDate: STEMI', 'AHA 2023 guideline']."),
    notes: z7.string().optional().describe("Detailed rationale.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    const { data, error } = await admin(ctx).from("content_reviews").insert({
      reviewer_id: ctx.getUserId(),
      content_type: input.content_type,
      content_id: input.content_id,
      verdict: input.verdict,
      severity: input.severity,
      reason: input.reason,
      sources_checked: input.sources_checked,
      notes: input.notes,
      reviewed_via: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Recorded ${input.verdict} (${input.severity}) on ${input.content_type} ${input.content_id}. Review id: ${data.id}` }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z8 } from "npm:zod@^3.25.76";
var list_reviews_default = defineTool8({
  name: "list_content_reviews",
  title: "List content reviews",
  description: "List existing review records to check what has already been reviewed and by whom.",
  inputSchema: {
    content_type: z8.enum(["qbank_question", "assessment_item", "atlas_conversation", "course_quiz"]).optional(),
    content_id: z8.string().optional(),
    verdict: z8.enum(["approved", "needs_revision", "rejected", "flagged"]).optional(),
    limit: z8.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const err = await requireAdmin(ctx);
    if (err) return { content: [{ type: "text", text: err }], isError: true };
    let q = admin(ctx).from("content_reviews").select("*").order("created_at", { ascending: false }).limit(input.limit);
    if (input.content_type) q = q.eq("content_type", input.content_type);
    if (input.content_id) q = q.eq("content_id", input.content_id);
    if (input.verdict) q = q.eq("verdict", input.verdict);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ count: data?.length ?? 0, reviews: data }, null, 2) }],
      structuredContent: { reviews: data }
    };
  }
});

// src/lib/mcp/tools/me.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/_shared.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
function sb(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireRole(ctx, role) {
  if (!ctx.isAuthenticated()) return "Not authenticated";
  const { data, error } = await sb(ctx).rpc("has_role", { _user_id: ctx.getUserId(), _role: role });
  if (error) return error.message;
  if (!data) return `${role} role required.`;
  return null;
}
async function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) return "Not authenticated";
  return null;
}
var errText = (msg) => ({ content: [{ type: "text", text: msg }], isError: true });
var okJson = (label, payload) => ({
  content: [{ type: "text", text: `${label}
${JSON.stringify(payload, null, 2)}` }],
  structuredContent: payload
});

// src/lib/mcp/tools/me.ts
var me_default = defineTool9({
  name: "me",
  title: "Get current user",
  description: "Return the signed-in user's profile, roles, and membership tier.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = await requireAuth(ctx);
    if (err) return errText(err);
    const client = sb(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      client.from("profiles").select("*").eq("user_id", uid).maybeSingle(),
      client.from("user_roles").select("role").eq("user_id", uid)
    ]);
    return okJson("Current user", {
      user_id: uid,
      email: ctx.getUserEmail(),
      roles: (roles ?? []).map((r) => r.role),
      profile
    });
  }
});

// src/lib/mcp/tools/my-courses.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.22.2";
var my_courses_default = defineTool10({
  name: "my_courses",
  title: "List my courses",
  description: "List courses the signed-in user is enrolled in (approved, invited, pending, or declined).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = await requireAuth(ctx);
    if (err) return errText(err);
    const { data, error } = await sb(ctx).from("course_enrollments").select("id, status, enrolled_at, courses:course_id (id, title, description, instructor_id, status)").eq("student_id", ctx.getUserId()).order("enrolled_at", { ascending: false });
    if (error) return errText(error.message);
    return okJson(`Enrollments (${data?.length ?? 0})`, { enrollments: data });
  }
});

// src/lib/mcp/tools/my-progress.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.22.2";
var my_progress_default = defineTool11({
  name: "my_progress",
  title: "Get my progress",
  description: "Return the signed-in user's latest score predictions and recent assessment attempts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = await requireAuth(ctx);
    if (err) return errText(err);
    const client = sb(ctx);
    const uid = ctx.getUserId();
    const [{ data: predictions }, { data: attempts }] = await Promise.all([
      client.from("usmle_score_predictions").select("*").eq("user_id", uid).order("created_at", { ascending: false }).limit(5),
      client.from("assessment_attempts").select("*").eq("user_id", uid).order("created_at", { ascending: false }).limit(10)
    ]);
    return okJson("Progress", { score_predictions: predictions, recent_attempts: attempts });
  }
});

// src/lib/mcp/tools/my-notifications.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z9 } from "npm:zod@^3.25.76";
var my_notifications_default = defineTool12({
  name: "my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's notifications, newest first.",
  inputSchema: {
    unread_only: z9.boolean().default(false),
    limit: z9.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    const err = await requireAuth(ctx);
    if (err) return errText(err);
    let q = sb(ctx).from("notifications").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return errText(error.message);
    return okJson(`Notifications (${data?.length ?? 0})`, { notifications: data });
  }
});

// src/lib/mcp/tools/my-taught-courses.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.22.2";
var my_taught_courses_default = defineTool13({
  name: "my_taught_courses",
  title: "List courses I teach",
  description: "List courses where the signed-in physician is the instructor. Requires physician role.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = await requireRole(ctx, "physician");
    if (err) return errText(err);
    const { data, error } = await sb(ctx).from("courses").select("id, title, description, status, created_at, updated_at").eq("instructor_id", ctx.getUserId()).order("updated_at", { ascending: false });
    if (error) return errText(error.message);
    return okJson(`Courses (${data?.length ?? 0})`, { courses: data });
  }
});

// src/lib/mcp/tools/list-course-students.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z10 } from "npm:zod@^3.25.76";
var list_course_students_default = defineTool14({
  name: "list_course_students",
  title: "List course students",
  description: "List enrollments for a course. Physician must be the instructor of the course.",
  inputSchema: {
    course_id: z10.string().uuid(),
    status: z10.enum(["invited", "pending", "approved", "declined", "rejected", "revoked"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id, status }, ctx) => {
    const err = await requireRole(ctx, "physician");
    if (err) return errText(err);
    const client = sb(ctx);
    const { data: course, error: cErr } = await client.from("courses").select("id, instructor_id, title").eq("id", course_id).maybeSingle();
    if (cErr) return errText(cErr.message);
    if (!course || course.instructor_id !== ctx.getUserId()) return errText("Not the instructor of this course.");
    let q = client.from("course_enrollments").select("id, status, enrolled_at, student_id, profiles:student_id (first_name, last_name)").eq("course_id", course_id).order("enrolled_at", { ascending: false });
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return errText(error.message);
    return okJson(`Roster for ${course.title} (${data?.length ?? 0})`, { enrollments: data });
  }
});

// src/lib/mcp/index.ts
var projectRef = "sljalqmlkpjtvtzjwfgx";
var mcp_default = defineMcp({
  name: "livemed-academy-review",
  title: "Livemed Academy \u2014 Content Review",
  version: "0.1.0",
  instructions: "Role-aware tools for Livemed Academy. Any signed-in user: me, my_courses, my_progress, my_notifications. Physicians: my_taught_courses, list_course_students. Platform admins: list_qbank_questions, get_qbank_question, search_content, list_atlas_conversations, get_atlas_conversation, get_course_quiz, flag_content_for_review, list_content_reviews. Each tool enforces its own role check via the OAuth-verified session.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    me_default,
    my_courses_default,
    my_progress_default,
    my_notifications_default,
    my_taught_courses_default,
    list_course_students_default,
    list_qbank_questions_default,
    get_qbank_question_default,
    search_content_default,
    list_atlas_conversations_default,
    get_atlas_conversation_default,
    get_course_quiz_default,
    flag_content_default,
    list_reviews_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
